### PR TITLE
Cmtice review experiment

### PR DESCRIPTION
**Pull request by dwblaikie**
Here's an experimental pull request (no need to ever approve it - just to experiment with email handling/etc)

### CODE REVIEW

**Comment by cmtice** [comment]
This is a test comment, to see what I do/don't see in email.

**Comment by dwblaikie** [comment]
> This is a test comment, to see what I do/don't see in email.

And a follow-up comment - I'd expect you'd get an email from this...

**Comment by cmtice** [comment]
This is a second comment to see if I've successfully fixed the issue.

**Comment by cmtice** [comment]
Hm...not yet. One more try.

**Comment by cmtice** [comment]
YES! That worked. :-)

**Comment by dwblaikie** [comment]
and one more from me, just to test that too!

**Pull request closed without merging**
